### ISSUE TITLE
Question: nvidia-smi

### ISSUE THREAD

**Issue by borgmanJeremy** [D34DC3N73R/netdata-glibc#1]
Can you elaborate on the step below means?

```
python.d.conf is the original with nvidia-smi=yes uncommented.
```
The conf file inside: https://github.com/coraxx/netdata_nv_plugin does not have anything related to nvidia-smi which makes me think this is the wrong folder to volume mount.

**Comment by D34DC3N73R** [comment]
The Nvidia plugin is built into netdata now but disabled by default. The line needs to be uncommented for the plugin to be activated. 

https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python.d.conf
https://docs.netdata.cloud/collectors/python.d.plugin/nvidia_smi/

**Comment by D34DC3N73R** [comment]
I made an edit to the build so this is no longer required.

**Comment by borgmanJeremy** [comment]
Thanks this worked great.
