### ISSUE TITLE
unknow nvidia runtime 

### ISSUE THREAD

**Issue by sniafas** [D34DC3N73R/netdata-glibc#2]
thanks for integrating nvidia-smi in netdata
I tried many times to reproduce it, but no luck.

Neither **docker run**/**nvidia-docker run** with `--runtime` option or **docker-compose** worked for me.
I am getting unknow runtime specified nvidia.

I have also added the configuration in daemon.json
Any ideas?

**Comment by D34DC3N73R** [comment]
Have you installed the [nvidia-docker package](https://github.com/NVIDIA/nvidia-docker)? If so, try restarting docker after saving the daemon.json edits.
```
sudo pkill -SIGHUP dockerd
sudo systemctl daemon-reload
sudo systemctl restart docker
```
If that doesn't work, try rebooting the computer. If that still doesn't work, reply back with your OS, and full run command and the output of `cat /etc/docker/daemon.json`.

**Comment by sniafas** [comment]
thanks, it worked
