### ISSUE TITLE
latest netdata releases not working?

### ISSUE THREAD

**Issue by kylrth** [D34DC3N73R/netdata-glibc#5]
I see the latest versioned tag on this image is `v1.31.0` and the `latest` tag uses netdata `v1.32.1-7-nightly`, while the `netdata/netdata` image has `v1.33.0`. Where are the latest releases?

**Comment by D34DC3N73R** [comment]
Thanks for the heads up on this. There was some issue with the workflow that is now resolved. I also manually pushed some more recent releases if you prefer to use stable builds.
