### ISSUE TITLE
Symbol not found /usr/bin/nvidia-smi

### ISSUE THREAD

**Issue by StephenShamakian** [D34DC3N73R/netdata-glibc#6]
Hello,

I just updated my Netdata container this morning after upgrading to v6.10-RC3 of Unraid and noticed the Nvidia Graphs were no longer loading. Looking in the Netdata container logs I am seeing this plugin load error:

`Error relocating /usr/bin/nvidia-smi: __strtok_r: symbol not found
Error relocating /usr/bin/nvidia-smi: __strdup: symbol not found
2022-03-17 15:24:04: python.d ERROR: nvidia_smi[nvidia_smi] : failed to invoke 'nvidia-smi' binary
2022-03-17 15:24:04: python.d INFO: plugin[main] : nvidia_smi[nvidia_smi] : check failed`

I'm pretty sure the v6.10-RC3 update to Unraid didn't affect this, as Netdata was working after the RC3 update. This started happening after clicking the "apply update" button for the Netdata container in Unraid.

Potentially unrelated: I notice this container image says there is an update almost every day in Unraid. Is that normal?

**Comment by D34DC3N73R** [comment]
Thanks for the heads up. I'm looking into this and I'm seeing the same behavior. The :latest image is based on netdata:latest and is a nightly type of build. With that said, I'd suggest using `d34dc3n73r/netdata-glibc:v1.33.0` the version tags are based on netdata release versions and should have some more stability.

**Comment by StephenShamakian** [comment]
@D34DC3N73R Thanks! I switched to v1.33.0 and the Nvidia graphs are back again. So if I'm not using latest tag, I'm assuming I will have to manually keep up to speed with their version releases?

**Comment by D34DC3N73R** [comment]
Yes, that would be the case as of now. :latest has been pretty stable, but if issues continue, I'll probably make a :stable tag that will be updated with the latest stable versions from netdata. Might not be a bad idea to implement that anyways.

**Comment by D34DC3N73R** [comment]
Traced the issue back to v2.25 glibc package. Reverted to v2.24 for now. I've also added the :stable tag which is built using netdata/netdata:stable. the :latest tag will fix itself on the next push.

**Comment by StephenShamakian** [comment]
Thanks @D34DC3N73R, I switched to stable and can confirm Nvidia-smi loads again.
