### ISSUE TITLE
v1.37.0 and v1.37.1 aren't on the hub

### ISSUE THREAD

**Issue by kylrth** [D34DC3N73R/netdata-glibc#8]
Is the automation broken again?

**Comment by D34DC3N73R** [comment]
I moved over to using `:stable` for the latest stable releases, but if you think it'd be good to have versions on there as well I can update the script.

**Comment by kylrth** [comment]
Oops, sorry; guess I should have read the recent history first. I'm used to upgrading manually by version number, but this is just fine by me.
